# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-06 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160806_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='title',
        ),
    ]
